language: c
sudo: required

# Enable travis validation
version: ~> 1.0

git:
  depth: 3
  quiet: true

addons:
  apt:
    update: true
    packages:
      - pkg-config csh cmake
      - gcc gfortran 
      - libgomp1 openmpi-bin libopenmpi-dev 
      - libnetcdf-dev libnetcdff-dev  netcdf-bin

env:
  global:
  - TYPE=ubuntu
  - FC=gfortran
  - OMPI_FC=${FC}

# stages:
#   - build_and_share
#   - download_and_deploy

script: ./build.sh ${TYPE} && tar -czvf binary_release.tar.gz $TRAVIS_BUILD_DIR/*
jobs:
  build_and_share:
    name: "Build archive and share"
    steps:
      - name: buildlib
      - name: uploadlib
        uses: actions/upload-artifact@v1
        with:
          name: library
          path: binary_release.tar.gz

  download_and_deploy:
    name: Download and deploy
    needs: build_and_share
    steps:
      - name: "Download archive"
        uses: actions/download-artifact@v1
        with:
          name: library
      - name: "deploy release"
        deploy:
          provider: releases
          api_key: '$GITHUB_API_KEY'
          skip_cleanup: true
          file: binary_release.tar.gz 
          on:
            repo: COSIMA/libaccessom2
            draft: true
            # tags: true
            branch: issue-45
