language: c
sudo: required

# Enable travis validation
version: ~> 1.0

git:
  depth: 3
  quiet: true

addons:
  apt:
    update: true
    packages:
      - pkg-config csh cmake
      - gcc gfortran 
      - libgomp1 openmpi-bin libopenmpi-dev 
      - libnetcdf-dev libnetcdff-dev  netcdf-bin

env:
  global:
  - TYPE=ubuntu
  - FC=gfortran
  - OMPI_FC=${FC}

# stages:
#   - build_and_share
#   - download_and_deploy

script: ./build.sh ${TYPE} && tar -czvf binary_release.tar.gz $TRAVIS_BUILD_DIR/*

deploy:
  - provider: releases
    api_key: '$GITHUB_API_KEY'
    skip_cleanup: true
    file: binary_release.tar.gz 
    on:
      repo: COSIMA/libaccessom2
      draft: true
      # tags: true
      all_branches: true
