language: c
sudo: required

git:
  depth: 3
  quiet: true

addons:
  apt:
    update: true
    packages:
      - pkg-config csh cmake
      - gcc gfortran 
      - libgomp1 openmpi-bin libopenmpi-dev 
      - libnetcdf-dev libnetcdff-dev  netcdf-bin

env:
  matrix:
  - TYPE=ubuntu
  global:
  - FC=gfortran
  - OMPI_FC=${FC}

jobs:
  include:
    - stage: test
      script: 
        - ./build.sh ${TYPE}
        - ls -l $TRAVIS_BUILD_DIR 
    - stage: GitHub Release
      script: 
        - ls -l $TRAVIS_BUILD_DIR 
        - tar -czvf binary_release.tar.gz $TRAVIS_BUILD_DIR/*
      deploy:
        provider: releases
        api_key: '$GITHUB_API_KEY'
        skip_cleanup: true
        on:
          repo: COSIMA/libaccessom2
          draft: true
          # tags: true
          branch: issue-45