name: Test libaccessom2 build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    uses: access-nri/workflows/.github/workflows/build-package.yml@main
    with:
      container-registry: ghcr.io
      container-name: access-nri/build-${{ github.event.repository.name }}-intel2021.1.2
      package-name: libaccessom2
      compiler-name: intel
      compiler-version: 2021.1.2
    permissions:
      packages: read
